compile for x86:
	./dockcross-x86 bash -c '$CC spectrev1.c -o spectre -static'

dockcross-x86:
	docker run --rm dockcross/linux-x86 > ./dockcross-x86
	chmod +x ./dockcross-x86

clean:
	rm -f dockcross-* hello64-static hello64-dynamic hello32-static
